### ISSUE TITLE
FEATURE: Add auto-selection of tags with minimum p value

### ISSUE THREAD

**Issue by mcrosson** [mcrosson/lr_plugin_computer_vision_tagging#3]
Add a feature for auto-selecting tags with a given minimum p value. The minimum p value should be an export preference.

Note this feature should not override the auto saving of tags.

**Comment by LowellMontgomery** [comment]
@mcrosson To clarify how this should work, this is intended to work as a modifier and affect current behavior as such:

If the p value is _not_ over the threshold and the terms is _not_ already associated with the image, this logic will DEselect the checkbox for that tag, even if it corresponds to a known keyword (one already in use on OTHER photos). Set very low, it means it would not change the behavior of the plugin at all; set very high, only a few returned tags would be selected. But it would never deselect a where the image already has that keyword. By "that keyword", at least in my logic, I compare after conversion to lower case.

I'd like to know more about the "auto-saving of tags" since some of the terms suggested by Clarifai are completely wrong, even where it has a very high p value. And I often frequently see that there are very appropriate terms that happened to have a lower priority (and so were not auto-selected by due to my p threshold — this being in my fork of the safx Clarifai Tagger.)

**Comment by mcrosson** [comment]
The planned implementation matches what you're describing. It won't de-select an existing tag and only auto-select a tag that's not part of the image and is over the threshold set by the end user.

@LowellMontgomery the auto-saving of tags is basically what you describe for auto-selection, only it saves the tags without prompt. I know there are some outliers that show up in the tag results from Clarifai but it's something a user has to turn on, it's up to them to decide if outliers are a problem or not.

**Comment by LowellMontgomery** [comment]
@mcrosson I guess that workflow could work if you took the time to review the results; you would end up with unwanted keywords on some images, but you could bulk remove them. With larger batches of images, bulk removal could mean fewer clicks. For such a workflow it might be convenient to be able to see all the images auto-tagged on a given day (create a collection, perhaps?) Then you could view the keywords in the collection and bulk-remove any particular keywords from many photos at once.

**Comment by mcrosson** [comment]
@LowellMontgomery the bulk image submissions is the use case I had in mind for auto tagging. You're right in that users will need a way to track what images were submitted and what tags were pulled by the computer vision APIs. On the project plan under "Phase Future (enhancements / features)" (see https://mcrosson.github.io/lr_plugin_computer_vision_tagging/project_plan/) I've got a note to create custom metadata and smart collections to facilitate working with previously submitted images. I do have an option to save json sidecar files with the Clarifai API responses as a stop gap measure for finding images that were tagged via the plugin.

**Comment by LowellMontgomery** [comment]
@mcrosson That sounds pretty well thought-out.
